plugins:
  - jekyll-archives
  - jekyll-paginate

highlighter: rouge
permalink: /:year/:month/:title

paginate: 10
paginate_path: "page/:num"

jekyll-archives:
  enabled: all
  layout: default
#   permalinks:
#     category: "/:category"
# collections:
#   categories:
#     output: true
#     permalink: /:categories
