---
layout: post
title: My computer got a cold.
categories:
- Miscellanea
tags: []
status: publish
type: post
published: true
meta: {}
---
As a nice treat this evening I picked up a worm for my computer. I was on a public wireless network, but only visiting safe sites; bbc, blogger etc. Bit of a shame really as it meant I had to do the decent thing and disconnect from the network and scan my computer to remove all traces. Internet security is a tough one, even if your a security obsesive like me. Still, I find these things quick and remove them quick. I picked up a common piece of malware the other day called 'winfixer'. I'm sure many of you have experienced this one. A quick search around the security zines and I found a tool called VundoFix to remove it. But for the general user, you should really only need two key pieces of software to keep you safe.<br /><br />Firstly, anti-virus. I will not at any point ever recommend Norton. It's crap. Not only is it not very effective, but as the most common piece of 'protection' it's normally the first that virus writers try to circumvent. Personally, I use AVG free edition, which did a great job for me tonight, as it has in the past. Though it's not 100% (what is?), it is very effective with all but the most obscure virus, trojan or worm. Another good free one is Avast home edition. I used to use this, but changed for no real reason other than AVG gives me more info. I like to know what my computer programs are up to. Paying for one should get you a better product, but I'm not recommending anything here as the two previously mentioned are effective enough for home users. I might mention though that McAfee once struck a deal with an adware company to let their software through for a certain fee.<br /><br />Secondly, anti-spyware/adware. I'm happy with my ad-aware SE personal by Lavasoft. Another free one, but does have some payable upgrades. I have tried others, for example, InfoWare's SpyRemover, but most of them have a habit of telling you that you have malware, but ask you to pay for removal. Ad-aware is a tried and tested classic who, like AVG and Avast, have large business divisions which subsidise free home use and ensure an up to date database.<br /><br />Many people would recommend getting an additional software firewall. I won't. Use the windows firewall and if you have anything like a router, use the hardware firewall. Software firewalls have raised all sorts of furore in security circles. They give a false impression of control by giving the user a allow/dis-allow pop-up every time they go to use a program that uses the internet. Also, because firewalls are deeply embeded into the system themselves they are good targets for an attacker, as the worm 'witty' showed.<br /><br />All in all, so long as you get your windows update every month, keep your anti-virus and adware up to date and run regular scans, think about what websites your using, you should be able to stop your computer from getting a nasty cold.
